###########################################################################################
#
#  STATAMIC CUSTOM ROUTES
#
###########################################################################################

routes:

  # user functions
  /register           : register
  /login              : login
  /forgotten-password : forgotten-password
  /reset-password     : reset-password
  
  /dashboard          : dashboard
  /profile            : profile
  
  
  # contact functions
  /contact/add      : contact/add
  /contact/search   : contact/search
  
  /contact/view/{contactid}  : contact/view
  /contact/edit/{contactid}  : contact/edit


ignore:
  # - success
